[package]
name = "aoc_utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "aoc_utils"
path = "src/lib.rs"
doc = true
edition = "2021"
crate-type = ["lib"]

[dependencies]
